### PR TITLE
move RedisNull to be internal to BinarySerializer

### PR DESCRIPTION
**Pull request by mapalan**
Fixes issue #125. Moves the class `RedisNull` to within `BinarySerializer` to allow using custom `ISerializer` implementations without needing to have a dependency on the `RedisNull` class.

### CODE REVIEW

**Comment by TimLovellSmith** [comment]
@mapalan Hmm.. why do redisNulls need to be serialized anyway?

**Comment by mapalan** [comment]
Any class that inherits from `NameObjectCollectionBase` [should support storing null values](https://docs.microsoft.com/en-us/dotnet/api/system.collections.specialized.nameobjectcollectionbase.baseset?view=netframework-4.8#System_Collections_Specialized_NameObjectCollectionBase_BaseSet_System_Int32_System_Object_). My understanding is that if a user tries to store a null value, a `RedisNull` object will be serialized to be stored in Redis in order to support that case.

**Comment by TimLovellSmith** [comment]
@mapalan OK you need to serialize the nullness somehow, but I still am not sure why the right way of storing 'nullness' is by serializing RedisNulls.

And I am not sure if this really addresses the issue. What are the repro steps?

**Comment by mapalan** [comment]
I created a sample test application that has its own implementation of Microsoft.Web.Redis.ISerializer, and did not need a dependency on RedisNull. The class is internal, meaning that it shouldn't be possible to have a dependency on it from a separate project anyways, so I'm not sure if there really is an issue. I should have investigated more before blindly committing anything... this is embarrassing 😓

**Pull request closed without merging**
