### PR TITLE
Updating redis client library

### PR DESCRIPTION
**Pull request by teonivalois**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@teonivalois__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by SiddharthChatrolaMs** [comment]
Please sign the CLA so that I can accept the pull request

**Comment by SiddharthChatrolaMs** [comment]
Leave a comment

**Comment by azurecla** [comment]
Hi __@teonivalois__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by SiddharthChatrolaMs** [comment]
This is available in following NuGet packages.
https://www.nuget.org/packages/Microsoft.Web.RedisSessionStateProvider/2.2.3
https://www.nuget.org/packages/Microsoft.Web.RedisOutputCacheProvider/1.7.3

**Pull request merged**
