### PR TITLE
Added support for multiple endpoints

### PR DESCRIPTION
**Pull request by filipeesch**
Added support for multiple redis endpoins separated by comma

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@filipeesch__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by filipeesch** [comment]
Got it. Where can I pass this connection string? I'm using the XML configuration of the site:

<caching>
  <outputCachedefault Provider="MyRedisOutputCache">
    <providers>
      
      <add name="MyRedisOutputCache" type="Microsoft.Web.Redis.RedisOutputCacheProvider" host="127.0.0.1" accessKey="" ssl="false"/>
    </providers>
  </outputCache>
</caching>

**Comment by JonCole** [comment]
It is documented here: https://github.com/Azure/aspnet-redis-providers/wiki/Configuration#connectionstring-valid-stackexchangeredis-connection-string-string

**Comment by filipeesch** [comment]
Thanks!

**Pull request closed without merging**
