### PR TITLE
Added ability to provide a certificate for authentication

### PR DESCRIPTION
**Pull request by treestobirds**
Exposed functionality in StackExchange.Redis that lets you provide a certificate for authentication.

See https://github.com/StackExchange/StackExchange.Redis/blob/master/StackExchange.Redis/StackExchange/Redis/ConfigurationOptions.cs

### CODE REVIEW

**Comment by joshuamckenty** [comment]
Is this still a relevant patch?

**Comment by jackholmes1010** [comment]
> Is this still a relevant patch?

Yes this is still relevant if you want to use with an SSL enabled Redis. At my previous company I ended up having to fork this project. Happy to fix conflicts and reopen this if anybody is interested.

**Comment by joshuamckenty** [comment]
Yes please! Let me know if you need help either from the asp or Redis side getting it cleaned up.

**Comment by jackholmes1010** [comment]
@joshuamckenty Here you go: https://github.com/Azure/aspnet-redis-providers/pull/124

I tested on a redislabs instance with ssl enabled.

## Steps I used to generate the pfx and base-64 encoded pfx
### Create pfx from crt and private key
```
openssl pkcs12 -export -in redislabs_user.crt -inkey redislabs_user_private.key -out mycert.pfx
```
### Convert pfx to base 64 string (using Powershell)
This step is optional as you can either provide a path to the pfx or a base-64 encoded version.
```powershell
$cert = get-content 'C:\path_to_your_pfx' -Encoding Byte
$certBase64 = [System.Convert]::ToBase64String($cert)
echo $certBase64
```

**Comment by slorello89** [comment]
To anyone stumbling by this issue looking for an answer.

There are two paths to set the Certificate selection with the StackExchange.Redis Library underpinning this provider:

1. Directly through the ConfigurationOptions object passed into the `Connect` method of the multiplexer
2. Via the Environment variables `SERedis_ClientCertPfxPath` (the path to your pfx file) and `SERedis_ClientCertPassword`(if password is necessary). Setting these environment variables will cause the ConnectionMultiplexer to use the desired certificate/password.

Might still be worth adding as Redis introduced TLS in Redis 6.0 so it's gone beyond an add-on feature to the enterprise providers (Redis, Azure, etc. . .)

**Pull request closed without merging**
