### PR TITLE
Resolving Race Condition

### PR DESCRIPTION
**Pull request by helioraptor**
resolving race condition [https://github.com/Azure/aspnet-redis-providers/issues/48](issue), adding unit test

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@helioraptor__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by helioraptor** [comment]
done

**Comment by azurecla** [comment]
Hi __@helioraptor__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by SiddharthChatrolaMs** [comment]
Can you please explain why this would be a race condition? Every request has their own copy of "ChangeTrackingSessionStateItemCollection" object. so why would there be a race condition? simple test app would be very helpful here.

**Comment by JonCole** [comment]
Rejected - see notes in #48.  ASP.NET does not support accessing HttpContext, Session or other related tasks from background threads.

**Pull request closed without merging**
